development:
  adapter: postgresql
  encoding: unicode
  database: refinery_database_development
  pool: 5
  username: tyrel
  password: SQL_BuddhA024878
  min_messages: warning
test:
  adapter: postgresql
  encoding: unicode
  database: refinery_database_test
  pool: 5
  username: tyrel
  password: SQL_BuddhA024878
  min_messages: warning
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d5mrtmuck7pc4a
  username: hqaxbskkvmocbl
  password: bjPB_Q-PzO8SrFxacvgezVH7LI
  host: ec2-23-21-130-189.compute-1.amazonaws.com
  port: 5432
